baseurl: "https://rinrio.netlify.app/"
title: R in Rio
theme: hugo-PaperMod
languageCode: pt-br
copyright: Pedro Cavalcante e Joao Pedro Oliveira
disqusShortname: XXX
googleAnalytics: XXX
pygmentsUseClasses: true
pygmentsCodefences: true


markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false

author:
  name: Time R in Rio
  profile: "https://google.com/+XXX"

taxonomies:
  tag: tags

params:
  mainSections:
    - post
  intro: true
  headline: R in Rio
  description: Ghostwriter example description
  github: "https://github.com/rinrio"
  gitlab: "https://gitlab.com/XXX"
  linkedin: "https://linkedin.com/in/XXX/"
  twitter: "https://twitter.com/XXX"
  stackoverflow: "https://stackoverflow.com/users/XXX/YYY"
  facebook: "https://www.facebook.com/username"
  email: rinriocurso@gmail.com
  opengraph: true
  shareTwitter: true
  shareFacebook: false
  shareGooglePlus: false
  shareLinkedIn: false
  dateFormat: "Mon, Jan 2, 2006"
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Tempo estimado de leitura:"
  fathomUrl: ""
  fathomSiteId: ""

permalinks:
  post: "/post/:year/:month/:day/:filename/"

menu:
  main:
    - name: Blog
      url: /
      weight: 1
    - name: Cursos
      url: /cursos/
      weight: 2
    - name: Contato
      url: /page/contact/
      weight: 3
    - name: Sobre
      url: /page/about/
      weight: 4
    - name: Material
      url: page/material/